pull_request_rules:
- actions:
    update: {}
  conditions:
  - base=20211013201159/test_update_action_on_closed_pr/main
  name: update
- actions:
    merge: {}
  conditions:
  - base=20211013201159/test_update_action_on_closed_pr/main
  - label=merge
  name: merge
