pull_request_rules:
- actions:
    request_reviews:
      users:
      - mergify-test1
  conditions:
  - base=20220519094100/test_request_reviews_clear_cache/main
  name: request_reviews
- actions:
    label:
      add:
      - ok
  conditions:
  - base=20220519094100/test_request_reviews_clear_cache/main
  - '#review-requested>0'
  name: request_reviews
