pull_request_rules:
- actions:
    label:
      add:
      - unstable
      - foobar
      remove:
      - stable
      - what
  conditions:
  - base=20211104085038/test_label/main
  name: rename label
