pull_request_rules:
- actions:
    rebase: {}
  conditions:
  - base=20220502110252/test_rebase_on_uptodate_pr_branch/main
  name: rebase
- actions:
    delete_head_branch: {}
    merge: {}
  conditions:
  - base=20220502110252/test_rebase_on_uptodate_pr_branch/main
  - label=merge
  name: merge
- conditions:
  - base=20220502110252/test_rebase_on_uptodate_pr_branch/main
  - label=update
  name: update
