pull_request_rules:
- actions:
    update: {}
  conditions:
  - base=20211013071517/test_update_action/main
  name: update
- actions:
    update: {}
  conditions:
  - base=20211013071517/test_update_action/main
  - label=merge
  name: merge
